/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto2.Clases.Reserva;
import proyecto2.EDD.ABB;
import proyecto2.EDD.TablaHash;

/**
 *
 * @author Giuseppe Vaccaro
 */
public class BuscarReservacion extends javax.swing.JFrame {

    public static Reserva reserva;
    private static TablaHash tablaEstado;
    private static ABB arbolReserva;
    private static ABB arbolHistorico;
    /**
     * Creates new form BuscarReservacion
     */
    public BuscarReservacion(Reserva reserva, TablaHash tablaEstado, ABB arbolReserva, ABB arbolHistorico) {
        initComponents();
        this.reserva = reserva;
        this.arbolReserva = arbolReserva;
        this.arbolHistorico = arbolHistorico;
        this.tablaEstado = tablaEstado;
        id.setText(reserva.getCi());
        name.setText(reserva.getNombre());
        lastName.setText(reserva.getApellido());
        sex.setText(reserva.getGenero());
        phone.setText(reserva.getCelular());
        tipoHab.setText(reserva.getTipoHabitacion());
        fechaLlegada.setText(reserva.getFechaLlegada());
        fechaSalida.setText(reserva.getFechaSalida());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Fondo = new Fondo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        tipoHab = new javax.swing.JTextField();
        fechaLlegada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(155, 164, 138));
        jLabel12.setText("Búsqueda de reservación");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 67, 67));
        jLabel1.setText("C.I.:");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 37, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Primer Nombre:");
        jLabel2.setEnabled(false);
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        jLabel3.setEnabled(false);
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Género");
        jLabel4.setEnabled(false);
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel6.setText("Teléfono");
        jLabel6.setEnabled(false);
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        fechaSalida.setEditable(false);
        fechaSalida.setEnabled(false);
        Fondo.add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 140, -1));

        id.setEditable(false);
        Fondo.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, -1));

        name.setEditable(false);
        name.setEnabled(false);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        Fondo.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, -1));

        lastName.setEditable(false);
        lastName.setEnabled(false);
        Fondo.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 190, -1));

        sex.setEditable(false);
        sex.setEnabled(false);
        Fondo.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 140, -1));

        phone.setEditable(false);
        phone.setEnabled(false);
        Fondo.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 220, -1));

        tipoHab.setEditable(false);
        tipoHab.setEnabled(false);
        Fondo.add(tipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 240, -1));

        fechaLlegada.setEditable(false);
        fechaLlegada.setEnabled(false);
        Fondo.add(fechaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 140, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel7.setText("Tipo de Habitación");
        jLabel7.setEnabled(false);
        Fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel8.setText("Fecha de Llegada");
        jLabel8.setEnabled(false);
        Fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Fecha de Salida");
        jLabel9.setEnabled(false);
        Fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        salir.setBackground(new java.awt.Color(159, 179, 159));
        salir.setText("Regresar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 147, 96));
        jLabel5.setText("Reservación");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(130, 147, 96));
        jLabel10.setText("Datos ");
        Fondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(155, 164, 138));
        jLabel13.setText("Búsqueda de reservación");
        Fondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        Fondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/logoreserv.png"))); // NOI18N
        Fondo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    //revisar validacion para los Jfield de los datos de reserv
    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        JOptionPane.showMessageDialog(null, "No se puede editar esta información","Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarReservacion(reserva, tablaEstado, arbolReserva, arbolHistorico).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JTextField fechaLlegada;
    private javax.swing.JTextField fechaSalida;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton salir;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField tipoHab;
    // End of variables declaration//GEN-END:variables

class Fondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen= new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
                    setOpaque(false);
                    
                    super.paint(g);
        }
    }

}
