/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import proyecto2.EDD.ABB;
import proyecto2.EDD.Excel;
import proyecto2.EDD.TablaHash;

/**
 *
 * @author Giuseppe Vaccaro
 */
public class Menu extends javax.swing.JFrame {
    
    public static TablaHash tablaEstado;
    public static ABB arbolReserva;
    public static ABB arbolHistorico;
    /**
     * Creates new form Menu
     */
    public Menu(TablaHash tablaEstado, ABB arbolReserva, ABB arbolHistorico) {
        initComponents();
        this.tablaEstado = tablaEstado;
        this.arbolReserva = arbolReserva;
        this.arbolHistorico = arbolHistorico;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        fondo = new Fondo();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        busquedaEstado = new javax.swing.JButton();
        busqeudaReserva = new javax.swing.JButton();
        historialHab = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/hotel.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel1.setText("Hotel Booking ");

        busquedaEstado.setBackground(new java.awt.Color(156, 173, 168));
        busquedaEstado.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        busquedaEstado.setForeground(new java.awt.Color(51, 51, 51));
        busquedaEstado.setText("Búsqueda de clientes");
        busquedaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaEstadoActionPerformed(evt);
            }
        });

        busqeudaReserva.setBackground(new java.awt.Color(156, 173, 168));
        busqeudaReserva.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        busqeudaReserva.setForeground(new java.awt.Color(51, 51, 51));
        busqeudaReserva.setText("Búsqueda de Reservación");
        busqeudaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqeudaReservaActionPerformed(evt);
            }
        });

        historialHab.setBackground(new java.awt.Color(156, 173, 168));
        historialHab.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        historialHab.setForeground(new java.awt.Color(51, 51, 51));
        historialHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/menu3.png"))); // NOI18N
        historialHab.setText("Historial del Habitación");
        historialHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialHabActionPerformed(evt);
            }
        });

        checkIn.setBackground(new java.awt.Color(156, 173, 168));
        checkIn.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        checkIn.setForeground(new java.awt.Color(51, 51, 51));
        checkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/menu1.png"))); // NOI18N
        checkIn.setText("Check in");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });

        checkOut.setBackground(new java.awt.Color(156, 173, 168));
        checkOut.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        checkOut.setForeground(new java.awt.Color(51, 51, 51));
        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/menu2.png"))); // NOI18N
        checkOut.setText("Check out");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2))
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busquedaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(busqeudaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkOut))
                            .addComponent(historialHab, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(busquedaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busqeudaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(historialHab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        // TODO add your handling code here:
        CheckIn iniciar = new CheckIn(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        iniciar.setVisible(true);
    }//GEN-LAST:event_checkInActionPerformed

    private void historialHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialHabActionPerformed
        // TODO add your handling code here:
        HistorialHabitaciones habitacion = new HistorialHabitaciones(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        habitacion.setVisible(true);
    }//GEN-LAST:event_historialHabActionPerformed

    private void busquedaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaEstadoActionPerformed
        // TODO add your handling code here:
        RegistroCliente cliente = new RegistroCliente(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        cliente.setVisible(true);
    }//GEN-LAST:event_busquedaEstadoActionPerformed

    private void busqeudaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqeudaReservaActionPerformed
        // TODO add your handling code here:
        ReservaMenu reserva = new ReservaMenu(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        reserva.setVisible(true);
    }//GEN-LAST:event_busqeudaReservaActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        // TODO add your handling code here:
        CheckOut salir = new CheckOut(tablaEstado, arbolReserva, arbolHistorico);
        this.dispose();
        salir.setVisible(true);
    }//GEN-LAST:event_checkOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(tablaEstado, arbolReserva, arbolHistorico).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busqeudaReserva;
    private javax.swing.JButton busquedaEstado;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton historialHab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
class Fondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen= new ImageIcon(getClass().getResource("/Imagenes/menu.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
                    setOpaque(false);
                    
                    super.paint(g);
        }
    }}
